In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

In [2]:
s1=pd.Series([1,2,3,4,5,6])

In [3]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
type(s1)

pandas.core.series.Series

In [5]:
s1=pd.Series([1,2,3,4],index=["a","b","c","d"])

In [6]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
data={"Name":["Alice","bob","shreya"],"Age":[20,21,22],"City":["mumbai","pune","bglr"]}

In [8]:
data

{'Name': ['Alice', 'bob', 'shreya'],
 'Age': [20, 21, 22],
 'City': ['mumbai', 'pune', 'bglr']}

In [9]:
type(data)

dict

In [10]:
df=pd.DataFrame(data)

In [11]:
df

     Name  Age    City
0   Alice   20  mumbai
1     bob   21    pune
2  shreya   22    bglr

In [12]:
df=pd.DataFrame(data,index=["Person1","Person2","Person3"])

In [13]:
df

           Name  Age    City
Person1   Alice   20  mumbai
Person2     bob   21    pune
Person3  shreya   22    bglr

In [14]:
df.index

Index(['Person1', 'Person2', 'Person3'], dtype='object')

In [16]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

# Creating dataframe from list

In [17]:
data=[[1,2,3],[4,5,6]]
data

[[1, 2, 3], [4, 5, 6]]

In [18]:
df=pd.DataFrame(data,columns=["A","B","C"],index=["D","E"])
df

   A  B  C
D  1  2  3
E  4  5  6

In [26]:
df=pd.read_excel(r"C:\Users\naiks\Downloads\Book1.xlsx")

In [27]:
df

      Name School  Marks
0  Shubham    BIT     45
1    Josua    RIT     56
2   Roshan    UIT     23
3  Jasmine    VIT     78
4   Shreya    PIT     12
5        A    KIT     89

In [28]:
df=pd.read_csv(r"C:\Users\naiks\dog_behavior_dataset.csv")
df

,dog_id,timestamp,neck_x,neck_y,neck_z,back_x,back_y,back_z,head_posture,body_posture,atomic_behavior,complex_behavior
0,Dog_01,2025-04-25 11:56:29.894279,0.786,0.859,-0.751,0.486,0.422,0.031,HeadDown,Lie,Lying,Abnormal|Abnormal|Abnormal
1,Dog_01,2025-04-25 11:56:29.914279,-0.138,0.596,-0.232,0.742,0.828,-0.991,HeadUp,Walk,Walking,Abnormal|Abnormal|Abnormal
2,Dog_01,2025-04-25 11:56:29.934279,-0.323,-0.709,-0.141,-0.180,-0.404,0.387,HeadUp,Walk,Walking,Abnormal|Abnormal|Abnormal
3,Dog_01,2025-04-25 11:56:29.954279,0.477,-0.369,-0.499,0.362,0.969,-0.704,Bark,Stand,Standing,Abnormal|Abnormal|Abnormal
4,Dog_01,2025-04-25 11:56:29.974279,0.482,-0.299,-0.500,-0.000,0.675,-0.638,Bark,Dig,Digging,Abnormal|Abnormal|Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Dog_01,2025-04-25 11:57:29.794279,0.871,0.915,0.867,-0.928,-0.743,0.772,HeadDown,Jump,Escaping,Abnormal|Abnormal|Abnormal
2996,Dog_01,2025-04-25 11:57:29.814279,-0.783,-0.979,0.613,-0.742,0.165,-0.448,HeadUp,Lie,Lying,Abnormal|Abnormal|Abnormal
2997,Dog_01,2025-04-25 11:57:29.834279,0.244,0.110,-0.537,-0.452,-0.690,-0.180,Bark,Stand,Standing,Abnormal|Abnormal|Abnormal
2998,Dog_01,2025-04-25 11:57:29.854279,-0.523,0.555,0.339,-0.771,0.211,-0.338,HeadUp,Sit,Sitting,Abnormal|Abnormal|Abnormal
2999,Dog_01,2025-04-25 11:57:29.874279,0.215,0.163,0.475,0.318,0.504,0.489,HeadDown,Walk,Sniffing,Abnormal|Abnormal|Abnormal

In [38]:
df=pd.read_json(r"C:\Users\naiks\Downloads\book1.json")
df

   Book_ID                Title        Author  Price
0        1        Python Basics    John Smith    350
1        2   Data Science Intro      Sara Lee    500
2        3     Machine Learning  David Miller    650
3        4  Deep Learning Guide   Emma Watson    800

In [39]:
iris='https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
df=pd.read_csv(iris)
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [44]:
#getting 1st 5 rows of data
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [47]:
#last 5 rows
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [42]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [48]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [51]:
df.shape

(150, 5)