# Pivot

In [1]:
import pandas as pd
data={"Name":["Alice","Bob","Charlie"],"Math":[89,78,87],"Science":[56,67,65],"English":[87,67,56]}

In [2]:
df=pd.DataFrame(data)
df

      Name  Math  Science  English
0    Alice    89       56       87
1      Bob    78       67       67
2  Charlie    87       65       56

In [3]:
df2=df.melt(id_vars=["Name"],value_vars=["Math","Science","English"],var_name="Subject",value_name="Score")
df2

      Name  Subject  Score
0    Alice     Math     89
1      Bob     Math     78
2  Charlie     Math     87
3    Alice  Science     56
4      Bob  Science     67
5  Charlie  Science     65
6    Alice  English     87
7      Bob  English     67
8  Charlie  English     56

In [4]:
df3=df2.pivot(index="Name",columns="Subject",values="Score")
df3

Subject  English  Math  Science
Name
Alice         87    89       56
Bob           67    78       67
Charlie       56    87       65

In [5]:
df3=df2.pivot(index="Name",columns="Subject",values="Score").reset_index()
df3

Subject     Name  English  Math  Science
0          Alice       87    89       56
1            Bob       67    78       67
2        Charlie       56    87       65

In [6]:
df3.columns.name=None
df3

      Name  English  Math  Science
0    Alice       87    89       56
1      Bob       67    78       67
2  Charlie       56    87       65

In [7]:
data={"Name":["Alice","Alice","Alice","Bob"],"Subject":["Math","Science","Math","Science"],
"Score":[80,90,70,65]}
df4=pd.DataFrame(data)
df4

    Name  Subject  Score
0  Alice     Math     80
1  Alice  Science     90
2  Alice     Math     70
3    Bob  Science     65

In [8]:
df4.pivot_table(index="Name",columns="Subject",values="Score",aggfunc="mean")

Subject  Math  Science
Name
Alice    75.0     90.0
Bob       NaN     65.0

# Group By

In [9]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
}) 
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  8 non-null      object
 1   Team        8 non-null      object
 2   Gender      8 non-null      object
 3   Salary      8 non-null      int64
 4   Age         8 non-null      int64
 5   JoinDate    8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 516.0+ bytes

In [11]:
df.groupby("Department")

In [12]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [13]:
df.groupby("Team")["Salary"].mean()

Team
A    87.5
B    81.5
C    90.0
D    77.5
Name: Salary, dtype: float64

In [14]:
df.groupby("Team")["Salary"].max()

Team
A    90
B    85
C    92
D    80
Name: Salary, dtype: int64

In [15]:
df.groupby("Team")["Salary"].min()

Team
A    85
B    78
C    88
D    75
Name: Salary, dtype: int64

In [16]:
df.groupby("Team")["Salary"].count()

Team
A    2
B    2
C    2
D    2
Name: Salary, dtype: int64

In [17]:
df.groupby("Team")["Salary"].sum()

Team
A    175
B    163
C    180
D    155
Name: Salary, dtype: int64

In [19]:
df.groupby(["Team","Gender"])["Salary"].max()

Team  Gender
A     F         90
      M         85
B     F         85
      M         78
C     F         88
      M         92
D     F         80
      M         75
Name: Salary, dtype: int64

In [20]:
df.groupby("Team")["Salary"].agg(["mean","max","min"])

      mean  max  min
Team
A     87.5   90   85
B     81.5   85   78
C     90.0   92   88
D     77.5   80   75

In [21]:
df.groupby("Team").agg({"Salary":"mean","Age":"max"})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [22]:
df["Team Average"]=df.groupby("Team")["Salary"].agg("mean")
df

  Department Team Gender  Salary  Age   JoinDate  Team Average
0         HR    A      M      85   23 2020-01-10           NaN
1         HR    A      F      90   25 2020-02-15           NaN
2         IT    B      M      78   30 2021-03-20           NaN
3         IT    B      F      85   22 2021-04-10           NaN
4  Marketing    C      M      92   28 2020-05-30           NaN
5  Marketing    C      F      88   26 2020-06-25           NaN
6      Sales    D      M      75   21 2021-07-15           NaN
7      Sales    D      F      80   27 2021-08-01           NaN

In [23]:
df.groupby("Team")["Salary"].agg("mean")

Team
A    87.5
B    81.5
C    90.0
D    77.5
Name: Salary, dtype: float64

In [24]:
df.groupby("Team")["Salary"].transform("mean")

0    87.5
1    87.5
2    81.5
3    81.5
4    90.0
5    90.0
6    77.5
7    77.5
Name: Salary, dtype: float64

In [25]:
df["Team Average"]=df.groupby("Team")["Salary"].transform("mean")
df

  Department Team Gender  Salary  Age   JoinDate  Team Average
0         HR    A      M      85   23 2020-01-10          87.5
1         HR    A      F      90   25 2020-02-15          87.5
2         IT    B      M      78   30 2021-03-20          81.5
3         IT    B      F      85   22 2021-04-10          81.5
4  Marketing    C      M      92   28 2020-05-30          90.0
5  Marketing    C      F      88   26 2020-06-25          90.0
6      Sales    D      M      75   21 2021-07-15          77.5
7      Sales    D      F      80   27 2021-08-01          77.5

In [26]:
df.groupby("Team").filter(lambda x:x["Salary"].mean()>80)

  Department Team Gender  Salary  Age   JoinDate  Team Average
0         HR    A      M      85   23 2020-01-10          87.5
1         HR    A      F      90   25 2020-02-15          87.5
2         IT    B      M      78   30 2021-03-20          81.5
3         IT    B      F      85   22 2021-04-10          81.5
4  Marketing    C      M      92   28 2020-05-30          90.0
5  Marketing    C      F      88   26 2020-06-25          90.0