# Data Cleaning

# Handling missing values

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\naiks\Downloads\data_cleaning_sample.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

# Checking for missing data

In [4]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

# Drop missing data

In [6]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [7]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [8]:
df.drop([0,3])

      Name   Age         City Gender              Email   Join Date
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [9]:
df.drop(columns=["Name","Age"])

          City Gender              Email   Join Date
0     New York      F  alice@example.com  01-05-2021
1        Delhi      M    charlie@example  20-07-2021
2  Los Angeles      M    bob@example.com  15-06-2020
3        Delhi      M    charlie@example  20-07-2021
4       Mumbai      M  david@example.com  12-11-2019
5        Delhi      F     eve@domain.com         NaN
6     New York      F  alice@example.com  01-05-2021
7     New York      F  alice@example.com  01-05-2021
8        Delhi      M    charlie@example  20-07-2021

# Filling missing data

In [10]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [12]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [14]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [15]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

# Detecting &removing duplicates

In [16]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [17]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [ ]:
#if name & age is same but email is not then
#  drop_duplicates(subset=["Email"])

In [19]:
df.drop_duplicates(subset=["Name"])

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

# String Operations

In [20]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [21]:
df["Name"].str.upper()

0      ALICE
1    CHARLIE
2        BOB
3    CHARLIE
4      DAVID
5        NaN
6      ALICE
7      ALICE
8    CHARLIE
Name: Name, dtype: object

In [22]:
df["City"].str.contains("delhi",case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [23]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

# Applying functions

In [24]:
df1=df.dropna()

In [25]:
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [26]:
df1["Age Group"]=df1["Age"].apply(lambda x:"Adult" if x>=25 else "Minor")

C:\Users\naiks\AppData\Local\Temp\ipykernel_19684\2364643972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Age Group"]=df1["Age"].apply(lambda x:"Adult" if x>=25 else "Minor")

In [27]:
df1

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [29]:
df1["Gender"]=df1["Gender"].map({"M":"Male","F":"Female"})

C:\Users\naiks\AppData\Local\Temp\ipykernel_19684\4154539174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Gender"]=df1["Gender"].map({"M":"Male","F":"Female"})

In [30]:
df1

    Name   Age         City  Gender              Email   Join Date Age Group
0  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult

In [33]:
df1["City"]=df1["City"].replace({"New York":"US","Mumbai":"Delhi"})  #
df1

C:\Users\naiks\AppData\Local\Temp\ipykernel_19684\2304251023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["City"]=df1["City"].replace({"New York":"US","Mumbai":"Delhi"})

    Name   Age         City  Gender              Email   Join Date Age Group
0  Alice  25.0           US  Female  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David  22.0        Delhi    Male  david@example.com  12-11-2019     Minor
6  Alice  25.0           US  Female  alice@example.com  01-05-2021     Adult
7  Alice  25.0           US  Female  alice@example.com  01-05-2021     Adult