# Merging & Joining

In [1]:
import pandas as pd
employee=pd.DataFrame({"EmpID":[1,2,3],
                      "Name":["Alice","Bob","Charlie"],
                      "DeptID":[10,20,30]})
employee

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [2]:
department=pd.DataFrame({"DeptID":[10,20,30],
                      "DeptName":["HR","Engineering","Marketing"],
                      })
department

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      30    Marketing

In [3]:
pd.merge(employee,department,on="DeptID")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30    Marketing

In [4]:
pd.merge(employee,department,how="inner",on="DeptID")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30    Marketing

In [5]:
pd.merge(employee,department,how="left",on="DeptID")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30    Marketing

In [6]:
pd.merge(employee,department,how="right",on="DeptID")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30    Marketing

In [7]:
pd.merge(employee,department,how="outer",on="DeptID")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30    Marketing

In [8]:
df1=pd.DataFrame({"Name":["Alice","Bob"]})

In [9]:
df2=pd.DataFrame({"Name":["Charlie","David"]})

In [10]:
df1

    Name
0  Alice
1    Bob

In [11]:
df2

      Name
0  Charlie
1    David

In [12]:
df3=pd.concat([df1,df2])
df3

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [13]:
df3.reset_index(drop=True)

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [14]:
pd.concat([df1,df2],axis=1)

    Name     Name
0  Alice  Charlie
1    Bob    David