In [25]:
import pandas as pd
df=pd.read_csv("heart_v2.csv")
df

     age  sex   BP  cholestrol  heart disease
0     70    1  130         322              1
1     67    0  115         564              0
2     57    1  124         261              1
3     64    1  128         263              0
4     74    0  120         269              0
..   ...  ...  ...         ...            ...
265   52    1  172         199              0
266   44    1  120         263              0
267   56    0  140         294              0
268   57    1  140         192              0
269   67    1  160         286              1

[270 rows x 5 columns]

In [26]:
df.shape

(270, 5)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            270 non-null    int64
 1   sex            270 non-null    int64
 2   BP             270 non-null    int64
 3   cholestrol     270 non-null    int64
 4   heart disease  270 non-null    int64
dtypes: int64(5)
memory usage: 10.7 KB

In [28]:
df.columns

Index(['age', 'sex', 'BP', 'cholestrol', 'heart disease'], dtype='object')

In [29]:
x=df.drop('heart disease',axis=1)
x

     age  sex   BP  cholestrol
0     70    1  130         322
1     67    0  115         564
2     57    1  124         261
3     64    1  128         263
4     74    0  120         269
..   ...  ...  ...         ...
265   52    1  172         199
266   44    1  120         263
267   56    0  140         294
268   57    1  140         192
269   67    1  160         286

[270 rows x 4 columns]

In [30]:
y=df['heart disease']
y

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: heart disease, Length: 270, dtype: int64

In [31]:
df.isnull()

       age    sex     BP  cholestrol  heart disease
0    False  False  False       False          False
1    False  False  False       False          False
2    False  False  False       False          False
3    False  False  False       False          False
4    False  False  False       False          False
..     ...    ...    ...         ...            ...
265  False  False  False       False          False
266  False  False  False       False          False
267  False  False  False       False          False
268  False  False  False       False          False
269  False  False  False       False          False

[270 rows x 5 columns]

In [32]:
df.isnull().sum()

age              0
sex              0
BP               0
cholestrol       0
heart disease    0
dtype: int64

In [33]:
df.isnull().sum().sum()

np.int64(0)

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((216, 4), (54, 4), (216,), (54,))

In [42]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    n_jobs=-1,
    oob_score=True,
    random_state=42,
)
model

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [43]:
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [44]:
model.oob_score_

0.6481481481481481

In [45]:
y_pred=model.predict(x_test)

In [46]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [47]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.76      0.74        33
           1       0.58      0.52      0.55        21

    accuracy                           0.67        54
   macro avg       0.65      0.64      0.64        54
weighted avg       0.66      0.67      0.66        54

In [48]:
print(accuracy_score(y_test,y_pred))

0.6666666666666666

In [49]:
print(confusion_matrix(y_test,y_pred))

[[25  8]
 [10 11]]