# Multiple Linear Regression

In [36]:
import pandas as pd
df=pd.read_csv("50_Startups.csv")

In [37]:
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [38]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [39]:
df.shape

(50, 5)

In [40]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [41]:
df.corr(numeric_only=True)

                 R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [42]:
x=df.iloc[:,:-1]

In [43]:
x

    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [44]:
y=df["Profit"]
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [45]:
#ML Algo cant take categorical value

In [46]:
states=pd.get_dummies(x['State'],drop_first=False)

In [47]:
states

    California  Florida  New York
0        False    False      True
1         True    False     False
2        False     True     False
3        False    False      True
4        False     True     False
5        False    False      True
6         True    False     False
7        False     True     False
8        False    False      True
9         True    False     False
10       False     True     False
11        True    False     False
12       False     True     False
13        True    False     False
14       False     True     False
15       False    False      True
16        True    False     False
17       False    False      True
18       False     True     False
19       False    False      True
20        True    False     False
21       False    False      True
22       False     True     False
23       False     True     False
24       False    False      True
25        True    False     False
26       False     True     False
27       False    False      True
28       False     True     False
29       False    False      True
30       False     True     False
31       False    False      True
32        True    False     False
33       False     True     False
34        True    False     False
35       False    False      True
36       False     True     False
37        True    False     False
38       False    False      True
39        True    False     False
40        True    False     False
41       False     True     False
42        True    False     False
43       False    False      True
44        True    False     False
45       False    False      True
46       False     True     False
47        True    False     False
48       False    False      True
49        True    False     False

In [48]:
states=pd.get_dummies(x['State'],drop_first=False,dtype=int)
states

    California  Florida  New York
0            0        0         1
1            1        0         0
2            0        1         0
3            0        0         1
4            0        1         0
5            0        0         1
6            1        0         0
7            0        1         0
8            0        0         1
9            1        0         0
10           0        1         0
11           1        0         0
12           0        1         0
13           1        0         0
14           0        1         0
15           0        0         1
16           1        0         0
17           0        0         1
18           0        1         0
19           0        0         1
20           1        0         0
21           0        0         1
22           0        1         0
23           0        1         0
24           0        0         1
25           1        0         0
26           0        1         0
27           0        0         1
28           0        1         0
29           0        0         1
30           0        1         0
31           0        0         1
32           1        0         0
33           0        1         0
34           1        0         0
35           0        0         1
36           0        1         0
37           1        0         0
38           0        0         1
39           1        0         0
40           1        0         0
41           0        1         0
42           1        0         0
43           0        0         1
44           1        0         0
45           0        0         1
46           0        1         0
47           1        0         0
48           0        0         1
49           1        0         0

In [49]:
x

    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [50]:
x=x.drop('State',axis=1)

In [51]:
x

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [54]:
x=pd.concat([x,states],axis=1)
x

,R&D Spend,Administration,Marketing Spend,California,Florida,New York,California,Florida,New York
0,165349.20,136897.80,471784.10,0,0,1,0,0,1
1,162597.70,151377.59,443898.53,1,0,0,1,0,0
2,153441.51,101145.55,407934.54,0,1,0,0,1,0
3,144372.41,118671.85,383199.62,0,0,1,0,0,1
4,142107.34,91391.77,366168.42,0,1,0,0,1,0
5,131876.90,99814.71,362861.36,0,0,1,0,0,1
6,134615.46,147198.87,127716.82,1,0,0,1,0,0
7,130298.13,145530.06,323876.68,0,1,0,0,1,0
8,120542.52,148718.95,311613.29,0,0,1,0,0,1
9,123334.88,108679.17,304981.62,1,0,0,1,0,0
10,101913.08,110594.11,229160.95,0,1,0,0,1,0
11,100671.96,91790.61,249744.55,1,0,0,1,0,0
12,93863.75,127320.38,249839.44,0,1,0,0,1,0
13,91992.39,135495.07,252664.93,1,0,0,1,0,0
14,119943.24,156547.42,256512.92,0,1,0,0,1,0
15,114523.61,122616.84,261776.23,0,0,1,0,0,1
16,78013.11,121597.55,264346.06,1,0,0,1,0,0
17,94657.16,145077.58,282574.31,0,0,1,0,0,1
18,91749.16,114175.79,294919.57,0,1,0,0,1,0
19,86419.70,153514.11,0.00,0,0,1,0,0,1
20,76253.86,113867.30,298664.47,1,0,0,1,0,0
21,78389.47,153773.43,299737.29,0,0,1,0,0,1
22,73994.56,122782.75,303319.26,0,1,0,0,1,0
23,67532.53,105751.03,304768.73,0,1,0,0,1,0
24,77044.01,99281.34,140574.81,0,0,1,0,0,1
25,64664.71,139553.16,137962.62,1,0,0,1,0,0
26,75328.87,144135.98,134050.07,0,1,0,0,1,0
27,72107.60,127864.55,353183.81,0,0,1,0,0,1
28,66051.52,182645.56,118148.20,0,1,0,0,1,0
29,65605.48,153032.06,107138.38,0,0,1,0,0,1
30,61994.48,115641.28,91131.24,0,1,0,0,1,0
31,61136.38,152701.92,88218.23,0,0,1,0,0,1
32,63408.86,129219.61,46085.25,1,0,0,1,0,0
33,55493.95,103057.49,214634.81,0,1,0,0,1,0
34,46426.07,157693.92,210797.67,1,0,0,1,0,0
35,46014.02,85047.44,205517.64,0,0,1,0,0,1
36,28663.76,127056.21,201126.82,0,1,0,0,1,0
37,44069.95,51283.14,197029.42,1,0,0,1,0,0
38,20229.59,65947.93,185265.10,0,0,1,0,0,1
39,38558.51,82982.09,174999.30,1,0,0,1,0,0
40,28754.33,118546.05,172795.67,1,0,0,1,0,0
41,27892.92,84710.77,164470.71,0,1,0,0,1,0
42,23640.93,96189.63,148001.11,1,0,0,1,0,0
43,15505.73,127382.30,35534.17,0,0,1,0,0,1
44,22177.74,154806.14,28334.72,1,0,0,1,0,0
45,1000.23,124153.04,1903.93,0,0,1,0,0,1
46,1315.46,115816.21,297114.46,0,1,0,0,1,0
47,0.00,135426.92,0.00,1,0,0,1,0,0
48,542.05,51743.15,0.00,0,0,1,0,0,1
49,0.00,116983.80,45173.06,1,0,0,1,0,0

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [26]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((40, 3), (10, 3), (40,), (10,))

In [29]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [30]:
model

LinearRegression()

In [31]:
model.fit(x_train,y_train)

LinearRegression()

In [32]:
y_pred=model.predict(x_test)

In [33]:
y_pred

array([114729.00768236,  90569.03231312,  75952.34861633,  70179.81117586,
       179539.15187896, 171638.15637459,  49624.94193162, 102253.12475568,
        58381.67907   ,  98240.74724733])

In [34]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)

In [35]:
score

0.9650940934427324

In [ ]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)